language: ruby
rvm:
  - 2.5.3
before_script:
  - psql 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:migrate
script:
  - bundle exec rails ci:tests
services:
  - postgresql
notifications:
  email: false
