language: ruby
rvm:
  - 2.5.3
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:migrate
script:
  - bundle exec rspec spec
  - bundle exec cucumber
  - yarn jest
  - yarn coveralls
services:
  - postgresql
notifications:
  email: false
